controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm1_p_joint
      - arm1_r_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
      - arm5_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_joint1
      - gripper_joint2
initial:  # Define initial robot poses per group
  - group: arm
    pose: zero