# arm_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - arm1_p_joint
#     - arm1_r_joint
#     - arm2_joint
#     - arm3_joint
#     - arm4_joint
#     - arm5_joint
#   gains:
#     arm1_p_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     arm1_r_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     arm2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     arm3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     arm4_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     arm5_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - gripper_joint1
#     - gripper_joint2
#   gains:
#     gripper_joint1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     gripper_joint2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: /irwb_full/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm1_p_joint
      - arm1_r_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
      - arm5_joint

  - name: /irwb_full/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_joint1
      - gripper_joint2